### ISSUE TITLE
Webpack 4

### ISSUE THREAD

**Issue by AuspeXeu** [vuetifyjs/webpack#16] opened 2018-07-10 20:48 UTC
Are there any plans to upgrade this to the latest webpack version?

**Comment by KaelWD** [comment] 2018-07-11 02:19
Duplicate of vuejs-templates/webpack#1280

https://github.com/vuejs-templates/webpack/pull/1369#issuecomment-401606517

**Closed by KaelWD** 2018-07-11 02:19 UTC
